server {
    listen 80;
    server_name _;
    client_max_body_size 210M;

    root /var/www/html/public;
    index index.php;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~* \.(css|js|png|jpg|jpeg|gif|ico|svg|woff2?|ttf)$ {
        try_files $uri =404;
        access_log off;
        expires 7d;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass api:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param HTTP_HOST $host;
        fastcgi_param HTTP_X_FORWARDED_HOST $host;
        fastcgi_param HTTP_X_FORWARDED_PROTO $scheme;
        fastcgi_param HTTP_X_FORWARDED_FOR $proxy_add_x_forwarded_for;
        fastcgi_param HTTPS off;
    }

    location ~ /\. {
        deny all;
    }
}
